import type { WeaponDef, WeaponId } from "./types";

export const WEAPONS: Record<WeaponId, WeaponDef> = {
  knife: {
    id: "knife",
    name: "Knife",
    cost: 0,
    damage: 45,
    fireDelay: 0.55,
    mag: 1,
    reserve: 0,
    spread: 0,
    speed: 520,
    range: 28,
    automatic: false,
  },
  glock: {
    id: "glock",
    name: "Glock-18",
    cost: 200,
    damage: 22,
    fireDelay: 0.18,
    mag: 20,
    reserve: 120,
    spread: 0.07,
    speed: 720,
    range: 520,
    automatic: false,
    team: "T",
  },
  usp: {
    id: "usp",
    name: "USP-S",
    cost: 200,
    damage: 34,
    fireDelay: 0.22,
    mag: 12,
    reserve: 24,
    spread: 0.04,
    speed: 780,
    range: 560,
    automatic: false,
    team: "CT",
  },
  ak47: {
    id: "ak47",
    name: "AK-47",
    cost: 2700,
    damage: 34,
    fireDelay: 0.1,
    mag: 30,
    reserve: 90,
    spread: 0.055,
    speed: 860,
    range: 700,
    automatic: true,
    team: "T",
  },
  m4: {
    id: "m4",
    name: "M4A4",
    cost: 3100,
    damage: 30,
    fireDelay: 0.09,
    mag: 30,
    reserve: 90,
    spread: 0.04,
    speed: 900,
    range: 720,
    automatic: true,
    team: "CT",
  },
  awp: {
    id: "awp",
    name: "AWP",
    cost: 4750,
    damage: 110,
    fireDelay: 1.35,
    mag: 5,
    reserve: 10,
    spread: 0.004,
    speed: 1400,
    range: 1100,
    automatic: false,
  },
};

export function defaultWeapon(team: "T" | "CT"): WeaponId {
  return team === "T" ? "glock" : "usp";
}
